# Generated by Django 6.0.5 on 2026-05-23 19:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'categories',
            },
        ),
        migrations.CreateModel(
            name='Commande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_commande', models.CharField(max_length=50, unique=True)),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('payee', 'Payée'), ('en_cours', 'En cours'), ('livree', 'Livrée'), ('annulee', 'Annulée')], default='en_attente', max_length=20)),
                ('montant_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('frais_livraison', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('methode_paiement', models.CharField(choices=[('mobile_money', 'Mobile Money'), ('carte', 'Carte'), ('livraison', 'Livraison')], max_length=20)),
                ('operateur_mobile', models.CharField(blank=True, max_length=50, null=True)),
                ('transaction_id', models.CharField(blank=True, max_length=200, null=True)),
                ('adresse_livraison', models.JSONField(blank=True, null=True)),
                ('note_client', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'commandes',
            },
        ),
        migrations.CreateModel(
            name='Utilisateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('mot_de_passe', models.CharField(max_length=255)),
                ('telephone', models.CharField(blank=True, max_length=20, null=True)),
                ('role', models.CharField(choices=[('client', 'Client'), ('admin', 'Admin')], default='client', max_length=10)),
                ('actif', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'utilisateurs',
            },
        ),
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('prix', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock', models.PositiveIntegerField(default=0)),
                ('image_principale', models.CharField(blank=True, max_length=300, null=True)),
                ('note_moyenne', models.DecimalField(decimal_places=2, default=0.0, max_digits=3)),
                ('nombre_avis', models.PositiveIntegerField(default=0)),
                ('actif', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('categorie', models.ForeignKey(db_column='categorie_id', on_delete=django.db.models.deletion.RESTRICT, to='boutique.categorie')),
            ],
            options={
                'db_table': 'produits',
            },
        ),
        migrations.CreateModel(
            name='CommandeItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_produit', models.CharField(max_length=255)),
                ('prix_unit', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantite', models.PositiveSmallIntegerField()),
                ('commande', models.ForeignKey(db_column='commande_id', on_delete=django.db.models.deletion.CASCADE, related_name='items', to='boutique.commande')),
                ('produit', models.ForeignKey(blank=True, db_column='produit_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='boutique.produit')),
            ],
            options={
                'db_table': 'commande_items',
            },
        ),
        migrations.CreateModel(
            name='ProduitImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chemin', models.CharField(max_length=300)),
                ('ordre', models.PositiveSmallIntegerField(default=0)),
                ('produit', models.ForeignKey(db_column='produit_id', on_delete=django.db.models.deletion.CASCADE, related_name='images', to='boutique.produit')),
            ],
            options={
                'db_table': 'produit_images',
                'ordering': ['ordre'],
            },
        ),
        migrations.AddField(
            model_name='commande',
            name='utilisateur',
            field=models.ForeignKey(blank=True, db_column='utilisateur_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='boutique.utilisateur'),
        ),
    ]
