# Generated by Django 4.2.30 on 2026-06-19 20:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('boutique', '0002_passwordresettoken'),
    ]

    operations = [
        migrations.CreateModel(
            name='Avis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.PositiveSmallIntegerField()),
                ('commentaire', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('produit', models.ForeignKey(db_column='produit_id', on_delete=django.db.models.deletion.CASCADE, related_name='avis', to='boutique.produit')),
                ('utilisateur', models.ForeignKey(db_column='utilisateur_id', on_delete=django.db.models.deletion.CASCADE, related_name='avis', to='boutique.utilisateur')),
            ],
            options={
                'db_table': 'avis',
                'unique_together': {('produit', 'utilisateur')},
            },
        ),
    ]
