# Generated by Django 5.0.4 on 2026-05-19 21:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boutique', '0001_initial'),
    ]

    operations = [
    ]
